version: "3.3"
services:
  app:
    build:
      context: ./app/.
      dockerfile: Dockerfile
    image: "php:7.4-fpm-alpine"
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    ports:
      - "9001:9001"
    volumes:
      - ./app:/var/www/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/supervisor/conf.d/:/etc/supervisor/conf.d/
      - ./storage/logs/supervisor/:/tmp/log/supervisor/
      - ./storage/logs/supervisor/workers:/tmp/log/supervisor/workers/
    networks:
       - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx_test
    restart: unless-stopped
    tty: true
    ports:
       - "9080:80"
       - "9443:443"
    volumes:
       - ./app:/var/www/app
       - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
       - ./storage/logs/nginx/:/var/log/nginx/
    networks:
      - app-network
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./storage/rabbitmq/:/var/lib/rabbitmq/
      - ./storage/logs/rabbitmq/:/var/log/rabbitmq
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
